[package]
name = "gpu"
version = "0.0.0"
edition = "2021"

[dependencies]
winit = { version = "0.29" }
wgpu = { version = "24.0.1" }
pollster = { version = "0.4.0" }
bytemuck = { version = "1.12.0", features = [ "derive" ] }
fontdue = "0.9.2"
