[package]
name = "gpu"
version = "0.0.0"
edition = "2021"

[dependencies]
winit = { version = "0.27.3" }
wgpu = { version = "0.14.0" }
pollster = { version = "0.2" }
bytemuck = { version = "1.9.1", features = [ "derive" ] }
image = { version = "0.24", default-features = false }
